version: 1
runners:
  Machine:
    config-id: 2
images:
  DeployMachine:
    image: ubuntu
    auth:
      username: << env.USER_NAME >>
      password: << env.USER_PASSWORD >>
jobs:
  Deploy_Brandfluence:
    steps:
      - apt-get update
      - apt-get -y install curl ca-certificates
      - curl -fsSL https://deb.nodesource.com/setup_20.x | bash -
      - apt-get install -y nodejs
      - npm i -g zcatalyst-cli
      - node -v
      - catalyst -v
      - npm install --omit=dev --prefix functions/brandfluence_api
      - npm install --omit=dev --prefix functions/bf_scheduler
      - SCHEDULER_SECRET='<< env.SCHEDULER_SECRET >>' node scripts/with-secrets.js catalyst deploy --project << env.PROJECT_NAME >> --org << env.CATALYST_ORG >> --token << env.CATALYST_TOKEN >>
stages:
  - name: build
    image: DeployMachine
    jobs:
      - Deploy_Brandfluence
